import React from "react";
import { Box } from "@mui/material";
import { Link } from "react-router-dom";
import MenzGuassaImage from "../../../assets/Menz-Guassa.jpg";

const containerStyle = {
  width: "100%",
  maxWidth: "1200px",
  margin: "0 auto",
  padding: "20px",
};

const breadcrumbStyle = {
  marginBottom: "20px",
};

const breadcrumbLinkStyle = {
  color: "#00ADB5",
  textDecoration: "none",
  fontSize: "1rem",
};

const breadcrumbTextStyle = {
  color: "#EEEEEE",
  fontSize: "1rem",
};

const heroStyle = {
  position: "relative",
  width: "100%",
  height: "400px",
  overflow: "hidden",
  borderRadius: "16px",
  marginBottom: "20px",
};

const heroImageStyle = {
  width: "100%",
  height: "100%",
  objectFit: "cover",
};

const heroTitleStyle = {
  position: "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  color: "#00ADB5",
  fontSize: "2.5rem",
  fontWeight: 600,
  textShadow: "2px 2px 4px rgba(0, 0, 0, 0.8)",
  textAlign: "center",
};

const contentStyle = {
  background: "rgba(57, 62, 70, 0.8)",
  padding: "20px",
  borderRadius: "16px",
  color: "#EEEEEE",
};

const textStyle = {
  fontSize: "1rem",
  lineHeight: "1.6",
  marginBottom: "15px",
};

const MenzGuassaPage = () => {
  return (
    <Box sx={{ background: "rgba(34, 40, 49, 0.8)", minHeight: "100vh" }}>
      <div style={containerStyle}>
        <div style={breadcrumbStyle}>
          <Link to="/" style={breadcrumbLinkStyle}>
            Home
          </Link>
          <span style={breadcrumbTextStyle}> / </span>
          <Link to="/national-parks" style={breadcrumbLinkStyle}>
            National Parks
          </Link>
          <span style={breadcrumbTextStyle}> / Menz Guassa</span>
        </div>
        <div style={heroStyle}>
          <img src={MenzGuassaImage} alt="Menz Guassa" style={heroImageStyle} />
          <h1 style={heroTitleStyle}>
            Menz Guassa Community Conservation Area
          </h1>
        </div>
        <div style={contentStyle}>
          <p style={textStyle}>
            Menz-Guassa Community Conservation Area (GCCA)’s stunning views and
            abundant wildlife make it a destination not to be missed.
          </p>
          <p style={textStyle}>
            Guassa Community Conservation Area is found in Amhara National
            Regional State, North Shoa Administrative Zone, and in Menz-Gera
            Midir Woreda (district), 260km northeast of Addis Ababa by road. The
            area is among the Ethiopian highlands’ most pristine and secluded
            natural wonders. Along the 90-minute drive (80km) from Tarmaber, the
            hustle and bustle of urban life fades into the slower pace of a
            traditional Menz village. The plateau itself promises breathtaking
            views and numerous endemic bird and wildlife species, including the
            iconic Ethiopian wolf (Canis simensis) and gelada (Theropiticus
            gelada).
          </p>
          <p style={textStyle}>
            The area is managed through a common property resource system by the
            communities living adjacent to the Guassa Area. This indigenous
            management system has been traced back to the 17th century and is
            one of the oldest conservation management systems in Sub-Saharan
            Africa. At present, Guassa user communities live in nine kebeles
            (farmers’ associations) adjacent to Guassa Community Conservation
            Area. The area is managed by the Guassa Conservation Council, which
            has kebele and woreda level components and consists of both
            community and local government representatives.
          </p>
          <p style={textStyle}>
            Ecotourism development in Guassa Community Conservation Area is
            being promoted by Frankfurt Zoological Society and local government
            in order to generate an alternative income for the Guassa user
            communities and to support management of the GCCA. The project has
            established the Guassa Community Lodge and designated wilderness
            camping grounds, which are managed by the Guassa Community Tourism
            Association on behalf of the Guassa council.
          </p>
          <p style={textStyle}>
            Guassa Community Conservation Area offers a wide variety of products
            and services, ranging from four-day treks to single night stays with
            short hikes. Visitors can discover a traditional Menz village and
            enjoy longer trekking experiences, mule rides, and overnight
            wilderness camping. The income generated by tourism is returned to
            the community and supports the conservation of the Guassa GCCA.
          </p>
        </div>
      </div>
    </Box>
  );
};

export default MenzGuassaPage;
